In [2]:
import numpy as np

## Some problems. Put your answers inside the print functions

In [15]:
a = np.arange(4).reshape((2,2))
print("array a:")
print(a)

print("\nMaximum value of a:")
print(np.max(a)) # put your answer inside the print

print("\nMinimum value of a:")
print(np.min(a)) # put your answer inside the print

print("\nReturn an array of the max in each column of a:")
print(np.max(a, axis=0))

print("\nReturn an array of the min in each row of a:")
print(np.amin(a, axis=1))

print("\nReturn a, sorted within each row:")
print(np.sort(a, axis=1))

print("\nReturn a, sorted within each column:")
print(np.sort(a, axis=0))


array a:
[[0 1]
 [2 3]]

Maximum value of a:
3

Minimum value of a:
0

Return an array of the max in each column of a:
[2 3]

Return an array of the min in each row of a:
[0 2]

Return a, sorted within each row:
[[0 1]
 [2 3]]

Return a, sorted within each column:
[[0 1]
 [2 3]]


In [7]:
b = np.arange(40).reshape((20,2))
print("array b:")
print(b)

print("\nPrint elements of the first column of b above that column's 80th percentile:")
min_score = np.percentile(b, 80, axis=0)[0]
#print(min_score)
for i in range(len(b[np.where(b[:,0] > min_score)])):
    print(b[np.where(b[:,0] > min_score)][i][0]) 

print("\nCovariance matrix of the columns of b:")

print(np.cov(b[:,0]), np.cov(b[:,1]))

array b:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]

Print elements of the first column of b above that column's 80th percentile:
32
34
36
38

Covariance matrix of the columns of b:
140.0 140.0
